-- return {
--   'codota/tabnine-nvim',
--   build = "./dl_binaries.sh",
--   config = function()
--     require('tabnine').setup({
--       disable_auto_comment = true,
--       accept_keymap = "<M-c>",
--       dismiss_keymap = "<C-]>",
--       debounce_ms = 800,
--       suggestion_color = { gui = "#808080", cterm = 244 },
--       codelens_color = { gui = "#808080", cterm = 244 },
--       codelens_enabled = true,
--       exclude_filetypes = { "TelescopePrompt", "NvimTree" },
--       log_file_path = nil,       -- absolute path to Tabnine log file,
--       tabnine_enterprise_host = tabnine_enterprise_host,
--       ignore_certificate_errors = false,
--     })
--   end
-- }

return {}
